apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-config
  namespace: vpn
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi