apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-config
  namespace: vpn
spec:
  storageClassName: local-path
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi