apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db
  namespace: sql
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-old
  namespace: sql
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi