apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-nextcloud-conf
  namespace: redis
  labels:
    app: redis-nextcloud
data:
  redis.conf: |
    port 6379
    dbfilename dumpNextCloud.rdb
    dir /data/
    save 50 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-stack-conf
  namespace: redis
  labels:
    app: redis-stack
data:
  redis.conf: |
    port 6379
    dir /data/
    save 50 10
    appendonly yes
    daemonize no
    loadmodule /opt/redis-stack/lib/redisearch.so
    loadmodule /opt/redis-stack/lib/redisgraph.so
    loadmodule /opt/redis-stack/lib/redistimeseries.so
    loadmodule /opt/redis-stack/lib/rejson.so
    loadmodule /opt/redis-stack/lib/redisbloom.so
    protected-mode no